spring:
  datasource:
    url : jdbc:h2:tcp://localhost/~/group6shoop
    username: group6
    password: group6
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size : 50
        show_sql : true
        format_sql : true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type : trace

cloud:
  aws:
    s3:
      bucket: lchs3bucket-12344231
    region:
      auto: false
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: AKIAVF6NB6G6G6ULSWFE
      secretKey: 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
      instanceProfile : true